# Generated by Django 2.2.2 on 2019-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XXTMP_PO_HEADERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_HEADER_ID', models.IntegerField(default=0)),
                ('operating_unit', models.CharField(max_length=120)),
                ('lookup_type', models.CharField(max_length=25)),
                ('operating_unit_country', models.CharField(max_length=60)),
                ('po_number', models.CharField(max_length=20)),
                ('pha_creation_date', models.DateTimeField(auto_now_add=True)),
                ('pha_last_update_date', models.DateTimeField(auto_now=True)),
                ('approved_date', models.DateTimeField()),
                ('po_currency', models.CharField(max_length=15)),
                ('buyer', models.CharField(max_length=240)),
                ('authorization_status', models.CharField(max_length=19)),
                ('vendor_name', models.CharField(max_length=240)),
                ('vendor_site_code', models.CharField(max_length=15)),
                ('po_terms', models.CharField(max_length=50)),
                ('bill_to_location_code', models.CharField(max_length=60)),
                ('ship_to_location_code', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='XXTMP_PO_LINES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_HEADER_ID', models.IntegerField(default=0)),
                ('PO_NUMBER', models.CharField(max_length=20)),
                ('PO_LINE_ID', models.IntegerField(default=0)),
                ('POL_CREATION_DATE', models.DateTimeField(auto_now_add=True)),
                ('POL_LAST_UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('LINE_NUM', models.IntegerField(default=0)),
                ('LINE_TYPE', models.CharField(max_length=25)),
                ('MAJOR_CATEGORY', models.CharField(max_length=40)),
                ('MINOR_CATEGORY', models.CharField(max_length=40)),
                ('PO_CATEGORY', models.CharField(max_length=81)),
                ('ITEM_NUMBER', models.CharField(max_length=40)),
                ('DESCRIPTION', models.CharField(max_length=240)),
                ('UOM', models.CharField(max_length=25)),
                ('POL_QUANTITY', models.FloatField(blank=True, default=None, null=True)),
                ('POL_UNIT_PRICE', models.FloatField(blank=True, default=None, null=True)),
                ('POL_UNIT_PRICE_USD', models.FloatField(blank=True, default=None, null=True)),
                ('POL_LINE_AMOUNT', models.FloatField(blank=True, default=None, null=True)),
                ('POL_LINE_AMOUNT_USD', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
