# Generated by Django 2.2.2 on 2019-06-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxtmp_po_lines',
            name='PO_HEADER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle_db.XXTMP_PO_HEADERS'),
        ),
    ]
