# Generated by Django 2.2.2 on 2019-06-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_db', '0002_auto_20190627_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xxtmp_po_headers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='xxtmp_po_lines',
            options={'managed': False},
        ),
    ]
