# Generated by Django 2.2.2 on 2019-06-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_db', '0003_auto_20190628_1853'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xxtmp_po_headers',
            table='XXTMP_PO_HEADERS',
        ),
        migrations.AlterModelTable(
            name='xxtmp_po_lines',
            table='XXTMP_PO_LINES',
        ),
    ]
